// Authentication
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// Menu
export const CLASSIFY_PAGE = "CLASSIFY_PAGE";
export const NOTEBOOK_PAGE = "NOTEBOOK_PAGE";
export const ANALYSIS_PAGE = "ANALYSIS_PAGE";
export const CLASSDOWNLOAD_PAGE = "CLASSDOWNLOAD_PAGE";
export const SEARCH_PAGE = "SEARCH_PAGE";

// Classification
export const SAVE_SUCCESS = "SAVE_SUCCESS";
export const SAVE_PROGRESS = "SAVE_PROGRESS";
export const SYNC_SUCCESS = "SYNC_SUCCESS";
export const SYNC_PROGRESS = "SYNC_PROGRESS";
export const NOTES_CHANGED = "NOTES_CHANGED";
export const NOTES_RECORDED = "NOTES_RECORDED";
export const REPLY_OPEN = "REPLY_OPEN";
export const REPLY_RESOLVED = "REPLY_RESOLVED";
export const NOTE_SUCCESS = "NOTE_SUCCESS";
export const NOTEBOOK_FILTERED = "NOTEBOOK_FILTERED";
export const TARGETS_BASIC_SEARCHED = "TARGETS_BASIC_SEARCHED";
export const BINS_BASIC_SEARCHED = "BINS_BASIC_SEARCHED";