# Generated by Django 3.2.4 on 2021-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='image',
        ),
        migrations.AddField(
            model_name='target',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
