# Generated by Django 3.2.4 on 2021-06-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0008_alter_target_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='bin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classify.bin'),
        ),
    ]
