# Generated by Django 3.2.4 on 2021-06-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0009_alter_set_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
