# Generated by Django 3.2.4 on 2021-07-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0019_alter_frontendpackage_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='scale',
            field=models.IntegerField(default=1),
        ),
    ]
