# Generated by Django 3.2.4 on 2021-07-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0020_target_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='scale',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='target',
            name='scale',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
