# Generated by Django 3.2.4 on 2021-07-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0021_auto_20210705_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendpackage',
            name='set',
            field=models.JSONField(default={'number': 1}),
            preserve_default=False,
        ),
    ]
