# Generated by Django 3.2.4 on 2022-01-10 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_preference', models.CharField(choices=[('AZ', 'Az'), ('ZA', 'Za'), ('LS', 'Ls'), ('SL', 'Sl')], default='AZ', max_length=2)),
                ('scale_preference', models.DecimalField(decimal_places=3, default='0.560', max_digits=5)),
                ('load_preference', models.CharField(choices=[('recent', 'Recent'), ('edited', 'Edited')], default='recent', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
