# Generated by Django 3.2.4 on 2022-03-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_preferences_phytoguide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'permissions': (('is_lab_user', 'Access Lab Classifying'),)},
        ),
    ]
