# Generated by Django 3.2.4 on 2022-03-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_preferences_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'permissions': (('is_lab_user', 'Can access lab classifying'), ('is_public_user', 'Can access public classifying'))},
        ),
    ]
