import React, { Component } from "react";
import { Redirect } from "react-router-dom";
import { connect } from 'react-redux';
import PropTypes from 'prop-types';
import Header from '../layout/Header';
import Pier17IFCB from "../../assets/IFCB-Pier17.jpeg";
import USGS from "../../assets/IFCB-USGS.jpeg";
import ceratium from "../../assets/ceratium-drawing.png";
import microscopePlankton from "../../assets/microscope-plankton.jpg";
import planktonCircle from "../../assets/plankton-circle-gradient-1.png";
import IFCBCircle from "../../assets/plankton-circle-gradient-2.png";
import dropdown from "../../icons/dropdown-blue.png";
import IFCBGreen from "../../icons/ifcb-green.png";
import computerGreen from "../../icons/computer-green.png";
import communityGreen from "../../icons/community-green.png";
import scientistGreen from "../../icons/scientist-green.png";
import flowArrow from "../../icons/flow-arrow-blue.png";
import flowArrowSide from "../../icons/flow-arrow-side-blue.png";

export class Landing extends Component {
    // TODO: Make hero into img and add alt text
    // media query smaller version when width is less than 950px

    static propTypes = {
        onHome: PropTypes.bool,
        onClassify: PropTypes.bool,
        onLearn: PropTypes.bool,
        onNotebook: PropTypes.bool,
        onAnalysis: PropTypes.bool,
      };

    expandBasics(element) {
        const section = document.getElementById(element);
        const dropdown = document.getElementById(element + '-dropdown');
        const image = document.getElementById(element + '-image');
        section.classList.toggle('hide');
        image.classList.toggle('hide');
        dropdown.classList.toggle('flip');
    }

    render() {

        if(this.props.onClassify) {
            return <Redirect push to="/classify" />
        }
        if(this.props.onHome) {
            return <Redirect push to="/" />
        }
        if(this.props.onNotebook) {
            return <Redirect push to="/notebook/" />
        }
        if(this.props.onAnalysis) {
            return <Redirect push to="/analysis/" />
        }

        return (
            <main>
                <Header location={this.props.location} />
                <div style={{'background-color':'#1fc85e'}}>
                    <div className='learn-hero'>
                        <h2 className='learn-title'>Learn</h2>
                    </div>
                </div>
                <div className='main'>
                    <div className='learn-page'>
                        <div className='learn-section-white learn-with-image'>
                            <h3 className='learn-heading'>Welcome to the Project</h3>
                            <p className='learn-body'>
                                This is a <span className='learn-text-highlight'>phytoplankton taxonomy annotation</span> project. 
                                <br/><br/>
                                The phytoplankton images on this site are generated by an Imaging FlowCytobot, or IFCB. The IFCB collects 
                                thousands of images of living phytoplankton cells daily, and transmits them to a computer over the internet. 
                                There are too many images to be identified by a human in real time, so we develop algorithms to automate the 
                                process.  
                                That’s what we’re doing here, with your help! 
                                <br/><br/>
                                Initially, it takes the eyes of a trained taxonomist to manually identify images and develop the algorithms. 
                                The more images we can collect and identify, the better our algorithm will perform. Once we have a functioning 
                                algorithm, we continue to correct and improve it over time. Having more people lend their eyes to the project 
                                will give us better results! 
                            </p>
                            <img alt='An IFCB, a big, black metal cylinder with a blue tube coming from the top, surrounded by other scientific 
                                monitoring instruments.' src={Pier17IFCB} className='learn-section-image'></img>
                        </div>
                        <div className='learn-section-blue'>
                            <div>
                                <h3 className='learn-heading learn-in-white'>The Basics</h3>
                                <img src={ceratium} className='ceratium-decor'></img>
                            </div>
                            <div className='basics-section'>
                                <img src={planktonCircle} className='basics-circle-image'></img>
                                <p className='basics-section-header'>Plankton</p>
                                <p className='basics-section-body'>
                                    {'Phytoplankton are tiny, single-celled organisms that drift with the ocean currents. '}
                                    <span className='hide' id='plankton-basics'>
                                        Like plants, many species of phytoplankton convert sunlight to energy through photosynthesis, though some types 
                                        can consume prey.
                                    </span>
                                </p>
                                <img alt='A variety of plankton seen through a microscope. The majority are long, tapered rectanges with a fluorescent blue and orange color.'
                                className='basics-section-image hide' id='plankton-basics-image' src={microscopePlankton}></img>
                                <img src={dropdown} className='basics-dropdown' id='plankton-basics-dropdown' onClick={() => this.expandBasics('plankton-basics')}/>
                            </div>
                            <div className='basics-section'>
                                <img src={IFCBCircle} className='basics-circle-image'></img>
                                <p className='basics-section-header'>IFCBs</p>
                                <p className='basics-section-body'>
                                    {'An IFCB is an automated microscope with a built-in camera that collects seawater. '} 
                                    <span className='hide' id='ifcb-basics'>
                                        The seawater flows through a tiny tube inside the instrument. Images of the 
                                        phytoplankton cells are taken as they pass one at a time in front of the camera.
                                        <br/><br/>
                                        The IFCB is a valuable tool because it runs by itself, around the clock, for weeks at a time. The IFCB collects 
                                        a seawater sample every 20 minutes, and can produce as many as 20,000 images an hour! All of the images are sent 
                                        over the internet to a computer.
                                    </span>
                                </p>
                                <img alt='A black metal cylinder with a tube at the top, the IFCB, strapped to a blue cabinet inside a boat.'
                                className='basics-section-image hide' id='ifcb-basics-image' src={USGS}></img>
                                <img src={dropdown} className='basics-dropdown' id='ifcb-basics-dropdown' onClick={() => this.expandBasics('ifcb-basics')}/>
                            </div>
                        </div>
                        <div className='learn-section-white'>
                            <h3 className='learn-heading'>How It Comes Together</h3>
                            <div>
                                <div className='flow-flex'>
                                    <div className='learn-flow-section left-section'>
                                        <div className='flow-graphics'>
                                            <p className='flow-number'>1</p>
                                            <img alt='Graphic showing the silhouette of an IFCB against a green circle.' src={IFCBGreen} className='flow-icon'></img>
                                        </div>
                                        <p className='flow-header'>Sample Collection</p>
                                        <p className='flow-body'>The IFCB collects seawater samples and takes images of the phytoplankton.</p>
                                    </div>
                                    <div className='learn-flow-section'>
                                        <div className='flow-graphics'>
                                            <p className='flow-number'>2</p>
                                            <img alt='Graphic showing the silhouette of an IFCB against a green circle.' src={computerGreen} className='flow-icon'></img>
                                        </div>
                                        <p className='flow-header'>Auto Classification</p>
                                        <p className='flow-body'>The images are run through algorithms that group the phytoplankton by species.</p>
                                    </div>
                                    <img src={flowArrow} className='flow-arrow-1-to-2'></img>
                                    <img src={flowArrowSide} className='flow-arrow-2-to-3'></img>
                                </div>
                                <div className='flow-flex'>
                                    <div className='learn-flow-section left-section'>
                                        <div className='flow-graphics'>
                                            <p className='flow-number'>4</p>
                                            <img alt='Graphic showing the silhouette of an IFCB against a green circle.' src={scientistGreen} className='flow-icon'></img>
                                        </div>
                                        <p className='flow-header'>Lab Classification</p>
                                        <p className='flow-body'>Scientists from the Kudela Lab review all community classifications, then use the data for their work.</p>
                                    </div>
                                    <div className='learn-flow-section'>
                                        <div className='flow-graphics'>
                                            <p className='flow-number'>3</p>
                                            <img alt='Graphic showing the silhouette of an IFCB against a green circle.' src={communityGreen} className='flow-icon'></img>
                                        </div>
                                        <p className='flow-header'>Community Classification</p>
                                        <p className='flow-body'>Community scientists find misclassifications and identify the species that befuddled the algorithm.</p>
                                    </div>
                                    <img src={flowArrow} className='flow-arrow-3-to-4'></img>
                                </div>
                            </div>
                        </div>
                        <div className='learn-section-blue plankton-decor'>
                            <h3 className='learn-heading learn-in-white'>Ocean Conservation Starts With You</h3>
                            <p className='learn-body learn-in-white learn-body-wide'>
                                Phytoplankton are vital to the health of our oceans, and our planet. Scientists use many tools to monitor the 
                                ever-changing phytoplankton community, but the vast and dynamic nature of the ocean makes the work challenging. 
                                Image recognition technology is one of the newest methods used for phytoplankton monitoring, and by participating 
                                in this project, you are taking part in cutting-edge science!
                            </p>
                        </div>
                        <div className='learn-section-white'>
                            <h3 className='learn-heading'>The Kudela Lab</h3>
                            <div>
                                <p className='learn-body learn-body-wide'>
                                    In the Kudela Lab at UC Santa Cruz, we use microscopes, satellites, robots, and good old fashioned chemistry to 
                                    understand phytoplankton. Phytoplankton are the unsung heroes of our planet, providing food for everything from krill 
                                    to whales, and producing much of the oxygen in our atmosphere. The dynamic and ever-changing phytoplankton community is 
                                    made up of thousands of different species, and we use an array of tools to examine what kinds are in the water at different 
                                    times and under different conditions. 
                                </p>
                                <a className='learn-button' href='http://oceandatacenter.ucsc.edu/'>Learn More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        );
    }
}

const mapStateToProps = state => ({
    onClassify: state.menu.onClassify,
    onHome: state.menu.onHome,
    onNotebook: state.menu.onNotebook,
    onAnalysis: state.menu.onAnalysis,
 });

 export default connect(mapStateToProps)(Landing);