# Generated by Django 3.2.4 on 2021-06-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_bin_classoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
