# Generated by Django 3.2.4 on 2021-06-30 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0005_bin_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.bin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bin',
            name='day',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bin',
            name='timeseries',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('bin', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='classify.bin')),
            ],
        ),
    ]
