# Generated by Django 3.2.4 on 2021-06-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0006_auto_20210630_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.bin'),
        ),
    ]
