# Generated by Django 3.2.4 on 2021-07-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0011_alter_target_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='bin',
        ),
    ]
