# Generated by Django 3.2.5 on 2021-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0022_frontendpackage_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoption',
            name='abbr',
            field=models.CharField(default='Ak', max_length=10),
            preserve_default=False,
        ),
    ]
