# Generated by Django 3.2.4 on 2021-07-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0028_target_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='scale',
        ),
        migrations.AddField(
            model_name='bin',
            name='ifcb',
            field=models.CharField(default='IFCB104', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeseriesoption',
            name='ifcb',
            field=models.CharField(default='IFCB104', max_length=15),
            preserve_default=False,
        ),
    ]
