# Generated by Django 3.2.4 on 2021-07-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0029_auto_20210720_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='ifcb',
        ),
    ]
