# Generated by Django 3.2.4 on 2021-07-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0030_remove_bin_ifcb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='ifcb',
            field=models.CharField(default='IFCB104', max_length=15),
            preserve_default=False,
        ),
    ]
