# Generated by Django 3.2.4 on 2021-07-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0031_bin_ifcb'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
