# Generated by Django 3.2.4 on 2021-07-25 00:23

from django.db import migrations, models
from django.db.migrations.operations.fields import RemoveField
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0033_auto_20210723_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('entry', models.CharField(max_length=220)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='classify.note')),
            ],
        ),
        migrations.RemoveField(
            model_name='bin',
            name='edited',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.AddField(
            model_name='bin',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.note'),
        ),
        migrations.RemoveField(
            model_name='target',
            name='notes'
        ),
        migrations.AddField(
            model_name='target',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.note'),
        ),
    ]
