# Generated by Django 3.2.4 on 2021-07-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0035_auto_20210726_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='classify.note'),
        ),
    ]
