# Generated by Django 3.2.4 on 2021-07-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0037_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.CharField(max_length=5),
        ),
    ]
