# Generated by Django 3.2.4 on 2021-07-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0038_alter_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ifcb',
            field=models.CharField(default='IFCB104', max_length=15),
        ),
    ]
