# Generated by Django 3.2.4 on 2021-07-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0039_note_ifcb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='ifcb',
            field=models.CharField(max_length=15),
        ),
    ]
