# Generated by Django 3.2.4 on 2021-08-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0042_auto_20210817_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoption',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
