# Generated by Django 3.2.4 on 2021-08-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0043_classoption_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='class_abbr',
            field=models.CharField(default='UNCL', max_length=10),
        ),
    ]
