# Generated by Django 3.2.4 on 2022-01-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0044_alter_target_class_abbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFCBImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='classoption',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='classoption',
            name='examples',
            field=models.ManyToManyField(blank=True, to='classify.IFCBImage'),
        ),
    ]
