# Generated by Django 3.2.4 on 2022-01-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0045_auto_20220114_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classoption',
            name='examples',
        ),
        migrations.AddField(
            model_name='classoption',
            name='examples',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='IFCBImage',
        ),
    ]
