# Generated by Django 3.2.4 on 2022-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0046_auto_20220114_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoption',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
