# Generated by Django 3.2.4 on 2022-01-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0047_alter_classoption_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoption',
            name='examples',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
