# Generated by Django 3.2.4 on 2022-01-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0048_alter_classoption_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoption',
            name='nonexamples',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
