# Generated by Django 3.2.4 on 2022-01-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0049_classoption_nonexamples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoption',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
