# Generated by Django 3.2.4 on 2022-03-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0050_alter_classoption_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeseries', models.CharField(max_length=15)),
                ('ifcb', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=4)),
                ('day', models.CharField(max_length=5)),
                ('file', models.CharField(max_length=17)),
            ],
        ),
        migrations.AddField(
            model_name='timeseriesoption',
            name='display_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='timeseriesoption',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PublicTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('class_name', models.CharField(default='Unclassified', max_length=120)),
                ('class_abbr', models.CharField(default='UNCL', max_length=10)),
                ('class_id', models.IntegerField(default='1')),
                ('editor', models.CharField(default='Auto Classifier', max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.bin')),
            ],
        ),
        migrations.CreateModel(
            name='PublicClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=120)),
                ('class_abbr', models.CharField(max_length=10)),
                ('class_id', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.publictarget')),
            ],
        ),
    ]
