# Generated by Django 3.2.4 on 2022-03-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0051_auto_20220318_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesoption',
            name='public_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
