# Generated by Django 3.2.4 on 2022-03-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0052_timeseriesoption_public_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publictarget',
            name='editor',
        ),
        migrations.AlterField(
            model_name='publictarget',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.publicbin'),
        ),
    ]
