# Generated by Django 3.2.4 on 2022-03-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0053_auto_20220321_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicclassification',
            name='editor',
            field=models.CharField(default='jamiewalton', max_length=50),
            preserve_default=False,
        ),
    ]
