# Generated by Django 3.2.4 on 2022-03-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0054_publicclassification_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictarget',
            name='auto',
            field=models.BooleanField(default=True),
        ),
    ]
