# Generated by Django 3.2.4 on 2022-03-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0055_publictarget_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictarget',
            name='editor',
            field=models.CharField(default='jamiewalton', max_length=50),
            preserve_default=False,
        ),
    ]
