# Generated by Django 3.2.4 on 2022-03-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0057_auto_20220323_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictarget',
            name='editor',
            field=models.ManyToManyField(to='classify.Editor'),
        ),
    ]
