# Generated by Django 3.2.4 on 2022-03-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0058_alter_publictarget_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publictarget',
            name='editor',
        ),
        migrations.AddField(
            model_name='editor',
            name='targets',
            field=models.ManyToManyField(to='classify.PublicTarget'),
        ),
    ]
