# Generated by Django 3.2.4 on 2022-03-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0059_auto_20220324_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='bins',
            field=models.ManyToManyField(to='classify.PublicBin'),
        ),
    ]
