# Generated by Django 3.2.4 on 2022-03-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0060_editor_bins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='bins',
            field=models.ManyToManyField(blank=True, to='classify.PublicBin'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='targets',
            field=models.ManyToManyField(blank=True, to='classify.PublicTarget'),
        ),
    ]
