# Generated by Django 3.2.4 on 2022-03-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0061_auto_20220324_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editor',
            new_name='Classifier',
        ),
    ]
