# Generated by Django 3.2.4 on 2022-05-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0063_classifier_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFilePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.JSONField()),
                ('classifier', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LabCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='frontendpackage',
            name='set',
        ),
    ]
