# Generated by Django 3.2.4 on 2022-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0064_auto_20220517_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityfilepackage',
            name='classifier',
            field=models.CharField(max_length=100),
        ),
    ]
