# Generated by Django 3.2.4 on 2022-05-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0065_alter_communityfilepackage_classifier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabCode',
        ),
    ]
