# Generated by Django 3.2.4 on 2022-05-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0066_delete_labcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='bins_categorized',
            field=models.ManyToManyField(blank=True, related_name='bins_categorized', to='classify.PublicBin'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='bins_identified',
            field=models.ManyToManyField(blank=True, related_name='bins_identified', to='classify.PublicBin'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='bins',
            field=models.ManyToManyField(blank=True, related_name='bins', to='classify.PublicBin'),
        ),
    ]
